version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: secret
      MONGO_INITDB_DATABASE: userdb
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
    driver: local
